language: perl
perl:
  - "5.24"
addons:
  postgresql: 9.6
services:
  - postgresql
install:
  - cpanm -n App::Sqitch DBD::Pg
before_script:
  - psql -U postgres -c 'create database testing'
script:
  - sqitch deploy --verify db:pg://postgres:@/testing
  - sqitch revert db:pg://postgres:@/testing -y
  - sqitch deploy --verify db:pg://postgres:@/testing
sudo: false
dist: trusty
notifications:
  email: false
